authors:
  mcherrera:
    name: Marco Contreras
    description: Creador
    avatar: https://github.com/mcherrera-cl.png
  
  fsantander:
    name: Francisco Santander
    description: Colaborador
    avatar: https://github.com/PathFinder2408.png
